### PR TITLE
Add Support for MT6765 Chipset (Realme) and improve script efficiency

### PR DESCRIPTION
**Pull request by eraselk**
eheheheheh

### CODE REVIEW

**Comment by Rem01Gaming** [comment]
```bash
        tp_path="/proc/touchpanel"
	write_val "1" $tp_path/game_switch_enable

        if [[ -e "$tp_path/oplus_tp_limit_enable" ]]; then
	write_val "0" $tp_path/oplus_tp_limit_enable
        fi

        if [[ -e "$tp_path/oppo_tp_limit_enable" ]]; then
        write_val "0" $tp_path/oppo_tp_limit_enable
        fi

       if [[ -e "$tp_path/oplus_tp_direction" ]]; then
       write_val "1" $tp_path/oplus_tp_direction
       fi

       if [[ -e "$tp_path/oppo_tp_direction" ]]; then
       write_val "1" $tp_path/oppo_tp_direction
       fi
```

`write_val()` Already check the file existence before echo'ing, there's no need to add `if` statement for check the file.

**Comment by eraselk** [comment]
@Rem01Gaming okh

**Comment by Rem01Gaming** [comment]
@Rem01Gaming Ini pula kenapa dobel

**Comment by Rem01Gaming** [comment]
@Rem01Gaming .

**Comment by eraselk** [comment]
@Rem01Gaming wait

**Comment by Rem01Gaming** [comment]
@Rem01Gaming Wtf

**Comment by Rem01Gaming** [comment]
Ok merged

**Pull request merged**
